# Generated by Django 3.1.2 on 2020-11-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(decimal_places=14, default=0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=14, default=0, max_digits=20)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='cloud',
            index=models.Index(fields=['name'], name='clouds_clou_name_1d5a42_idx'),
        ),
    ]
